name: Bug Report
description: Signaler un bug ou un problème
title: "[BUG] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Merci de signaler ce bug ! Veuillez fournir autant de détails que possible.

  - type: textarea
    id: description
    attributes:
      label: Description du bug
      description: Une description claire et concise du bug
      placeholder: "Décrivez le bug rencontré..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Étapes pour reproduire
      description: Comment reproduire le bug ?
      placeholder: |
        1. Aller sur '...'
        2. Cliquer sur '...'
        3. Scroller jusqu'à '...'
        4. Observer l'erreur
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      description: Que devrait-il se passer normalement ?
      placeholder: "Description du comportement attendu..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportement actuel
      description: Que se passe-t-il actuellement ?
      placeholder: "Description du comportement actuel..."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Logs
      description: Si applicable, ajoutez des screenshots ou des logs
      placeholder: "Collez vos screenshots ou logs ici..."
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environnement
      description: Informations sur votre environnement
      placeholder: |
        - OS: [e.g. macOS, Windows, Linux]
        - Navigateur: [e.g. Chrome, Firefox, Safari]
        - Version: [e.g. 22]
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Sévérité
      description: Quelle est la sévérité de ce bug ?
      options:
        - Low - Problème mineur
        - Medium - Affecte certaines fonctionnalités
        - High - Bloque des fonctionnalités importantes
        - Critical - Application inutilisable
    validations:
      required: true
